### ISSUE TITLE
ServiceLocatorAwareInterface is deprecated 

### ISSUE THREAD

**Issue by guilherme90** [zendframework/zend-diagnostics#81]
Hi...

I found a error when run `diagnostics`.

![error](https://user-images.githubusercontent.com/2879939/29175485-930173d6-7dbf-11e7-9ee8-f82a2f8ba394.png)

**Comment by weierophinney** [comment]
This is a problem with the controller generated by ZFTool, and should be [reported against the ZFTool component](https://github.com/zendframework/ZFTool/issues).

Unfortunately, ZFTool has not been updated in quite some time, and at this point is unlikely to get further fixes (mainly due to having a hard-to-maintain architecture).
